# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Allow local connections
local   all             all                                     trust

# Allow inter-node communication within Docker network (trust within 172.x range)
host    all             all             172.0.0.0/8             trust

# Allow connections from host
host    all             all             0.0.0.0/0               md5